export interface Letter {
  letter: string;
}
export interface Letters extends Letter {
  letters: Letter[];
}

let letters = [
  "a",
  "б",
  "в",
  "г",
  "д",
  "е",
  "ё",
  "ж",
  "з",
  "и",
  "й",
  "к",
  "л",
  "м",
  "н",
  "о",
  "п",
  "р",
  "с",
  "т",
  "у",
  "ф",
  "х",
  "ц",
  "ч",
  "ш",
  "щ",
  "ъ",
  "ы",
  "ь",
  "э",
  "ю",
  "я",
];
export default letters;
// let lettersObj: Array<ILetter> = [
//   { cyr: "a", lat: "a" },
//   { cyr: "б", lat: "b" },
//   { cyr: "в", lat: "v" },
//   { cyr: "г", lat: "g" },
//   { cyr: "д", lat: "d" },
//   // { cyr: "е", lat: "je" },
//   // { cyr: "ё", lat: "jo" },
//   // { cyr: "ж", lat: "zh" },
//   // { cyr: "з", lat: "z" },
//   // { cyr: "л", lat: "l" },
//   // { cyr: "м", lat: "m" },
//   // { cyr: "н", lat: "n" },
//   // { cyr: "о", lat: "o" },
//   // { cyr: "п", lat: "p" },
//   // { cyr: "р", lat: "r" },
//   // { cyr: "с", lat: "s" },
//   // { cyr: "т", lat: "t" },
//   // { cyr: "у", lat: "y" },
//   // { cyr: "ф", lat: "f" },
//   // { cyr: "х", lat: "h" },
//   // { cyr: "ц", lat: "c" },
//   // { cyr: "ч", lat: "ch" },
//   // { cyr: "ш", lat: "sh" },
//   // { cyr: "щ", lat: "sch" },
//   // { cyr: "ъ", lat: `"` },
//   // { cyr: "ы", lat: "y" },
//   // { cyr: "ь", lat: `'` },
//   // { cyr: "э", lat: "e" },
//   // { cyr: "ю", lat: "ju" },
//   // { cyr: "я", lat: "ja" },
// ];
// export default lettersObj;
