export interface ILetter {
  cyr: string;
  lat: string;
}

// interface Iletter{
//   letters:Letter[]
// }

let lettersObj: Array<ILetter> = [
  { cyr: "а", lat: "a" },
  { cyr: "А", lat: "A" },
  { cyr: "б", lat: "b" },
  { cyr: "Б", lat: "B" },
  { cyr: "в", lat: "v" },
  { cyr: "В", lat: "V" },
  { cyr: "г", lat: "g" },
  { cyr: "Г", lat: "G" },
  { cyr: "д", lat: "d" },
  { cyr: "Д", lat: "D" },
  { cyr: "е", lat: "je" },
  { cyr: "Е", lat: "Je" },
  { cyr: "ё", lat: "jo" },
  { cyr: "Ё", lat: "Jo" },
  { cyr: "ж", lat: "zh" },
  { cyr: "Ж", lat: "Zh" },
  { cyr: "з", lat: "z" },
  { cyr: "З", lat: "Z" },
  { cyr: "и", lat: "i" },
  { cyr: "И", lat: "I" },
  { cyr: "й", lat: "j" },
  { cyr: "Й", lat: "J" },
  { cyr: "к", lat: "k" },
  { cyr: "К", lat: "K" },
  { cyr: "л", lat: "l" },
  { cyr: "Л", lat: "L" },
  { cyr: "м", lat: "m" },
  { cyr: "М", lat: "M" },
  { cyr: "н", lat: "n" },
  { cyr: "Н", lat: "N" },
  { cyr: "о", lat: "o" },
  { cyr: "О", lat: "O" },
  { cyr: "п", lat: "p" },
  { cyr: "П", lat: "P" },
  { cyr: "р", lat: "r" },
  { cyr: "Р", lat: "R" },
  { cyr: "с", lat: "s" },
  { cyr: "С", lat: "S" },
  { cyr: "т", lat: "t" },
  { cyr: "Т", lat: "T" },
  { cyr: "у", lat: "u" },
  { cyr: "У", lat: "U" },
  { cyr: "ф", lat: "f" },
  { cyr: "Ф", lat: "F" },
  { cyr: "х", lat: "h" },
  { cyr: "Х", lat: "H" },
  { cyr: "ц", lat: "c" },
  { cyr: "Ц", lat: "C" },
  { cyr: "ч", lat: "ch" },
  { cyr: "Ч", lat: "Ch" },
  { cyr: "ш", lat: "sh" },
  { cyr: "Ш", lat: "Sh" },
  { cyr: "щ", lat: "sch" },
  { cyr: "Щ", lat: "Sch" },
  { cyr: "ъ", lat: `"` },
  { cyr: "Ъ", lat: `"` },
  { cyr: "ы", lat: "y" },
  { cyr: "Ы", lat: "Y" },
  { cyr: "ь", lat: `'` },
  { cyr: "Ь", lat: `'` },
  { cyr: "э", lat: "e" },
  { cyr: "Э", lat: "E" },
  { cyr: "ю", lat: "ju" },
  { cyr: "Ю", lat: "Ju" },
  { cyr: "я", lat: "ja" },
  { cyr: "Я", lat: "Ja" },
  { cyr: " ", lat: " " },
  { cyr: ",", lat: "," },
  { cyr: ".", lat: "." },
  { cyr: "!", lat: "!" },
  { cyr: ":", lat: ":" },
];

export default lettersObj;
// a: "a",
// b:"б",
// v:"в",
// g:"г",
// d:"д",
// e:"е",
// yo:"ё",
// zh:"ж",
// z: "з",
// i: "и",
// j:"й",
// k:"к",
// l: "л",
// n:"н",
// o:"о",
// p:"п",
// "р",
// "с",
// "т",
// "у",
// "ф",
// "х",
// "ц",
// "ч",
// "ш",
// "щ",
// "ъ",
// "ы",
// "ь",
// "э",
// "ю",
// "я",
